### ISSUE TITLE
[Android] [UI] As a user, I can see the job details page

### ISSUE THREAD

**Issue by luongvo** [nimblehq/android-kmm-showcases#3]
## Why

As we're creating a demo to show job detail, the user should be able to read the details of a job, including price, location, time, etc before deciding to accept the jobs or not.

## Acceptance Criteria

On job detail screen:
- Implement the title bar with title `Job Detail` and back icon in black `#171923`
- Implement a sticky bottom bar:
  - Show the description as `Get this job to know more about farmer contact information` in black `#171923`
  - Show the price label in black `#171923` and price value `80-95 Baht` green `#2BC65D`
  - Show the `Accept` button in green background `#2BC65D` and white text color `#FFFFFF`

## Design

![image](https://user-images.githubusercontent.com/16315358/158977748-12dfd751-81a6-43a0-a55a-ae4ff255b232.png)

## Resources

- ![ic_back](https://user-images.githubusercontent.com/16315358/158978756-bf1c7584-d3fb-4738-a49f-51931dfd85db.svg)

**Comment by lydiasama** [comment]
@luongvo When pressing the back button, what screen it will lead to? Do we show this screen as the first screen?

**Comment by hoangnguyen92dn** [comment]
@lydiasama I think we could skip the back button. Just show on the UI with no action.

**Comment by lydiasama** [comment]
@hoangnguyen92dn I think so. Can we get rid of the back icon on the toolbar? @luongvo

**Comment by luongvo** [comment]
@lydiasama please keep it as we're trying to produce to same UI, we might have another screens in next Growth showcases
